version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mynameisviii.com
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
permissions:
  - object: /var/www/mynameisviii.com
    mode: 644
    owner: ec2-user
    type:
      - directory
  - object: /var/www/mynameisviii.com
    mode: 755
    owner: ec2-user
    type:
      - file
