version: 0.2
phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | bash -
      - apt-get install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn tsc
      - yarn lint
      - yarn test
      - yarn build
  post_build:
    commands:
artifacts:
  files:
    - node_modules/**/*
    - dist/**/*
    - locales/**/*
    - scripts/**/*
    - appspec.yml
    - next.config.js
    - next.routes.js
    - next.server.js
    - package.json
    - yarn.lock
cache:
  paths:
    - node_modules/**/*
